apiVersion: v1
kind: Service
metadata:
  name: ftps-srv
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  selector:
    app: ftps
  ports:
    - port: 21
      name: ftps
      protocol: TCP
      targetPort: 21
    - port: 50100
      name: filez
      protocol: TCP
      targetPort: 50100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 50100

