apiVersion: v1
kind: Service
metadata:
  name: grafana-srv
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  selector:
    app: grafana
  ports:
    - port: 3000
      name: grafana
      protocol: TCP
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

