apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-srv
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
